### ISSUE TITLE
Plugin with id 'com.android.library' not found

### ISSUE THREAD

**Issue by MisterBowie** [imyyq-star/MVVMArchitecture#2]
AS：3.6.2

Build file '/Users/shubowei/公司/源码/ropeskipping/MVVMArchitecture/build.gradle' line: 1
A problem occurred evaluating root project 'MVVMArchitecture'.
> Plugin with id 'com.android.library' not found.

**Comment by imyyq-star** [comment]
框架并不是一个完整的 AS 项目，而是一个 Android Module，所以你不能直接 open 它，而是需要把它作为你项目的一个 Module 引入，详见 Wiki，[1、引入框架](https://github.com/imyyq-star/MVVMArchitecture/wiki/1%E3%80%81%E5%BC%95%E5%85%A5%E6%A1%86%E6%9E%B6)

**Comment by MisterBowie** [comment]
我先试一下
