### ISSUE TITLE
看图

### ISSUE THREAD

**Issue by qhzzl** [imyyq-star/MVVMArchitecture#21]
![1632710318(1)](https://user-images.githubusercontent.com/19565325/134837897-1ad22c15-64f6-4e2b-aed1-7021fa8449dd.png)

**Comment by imyyq-star** [comment]
框架 1.0.6 版本使用了当时的 ActivityResult，是 Alpha 版本的，Alpha 实际上不应该使用到正式版中的，我疏忽了，而你的项目应该是用了正式版，覆盖了框架的 Alpha 版本。
后来 ActivityResult API 在正式版有改动，必须在 Activity 状态是 START 及之前，就创建注册好 ActivityResultContracts。框架是在 Resume 时才创建注册，所以就有如图的崩溃。

目前对于 ActivityResult 只使用到了 for result 的功能，原本的 startActivityForResult 其实够用了。
建议如果是远程仓库引入，不要用框架的 startActivityForResult 方法了。
如果是源码引入，可以自行更改相关代码，换成原生的 startActivityForResult 方法。
